import { Geist, Geist_Mono } from "next/font/google";
import Providers from "@/context/Providers";
import "@/styles/main.scss";
import { ActionsProvider } from "@/context/actionsProvider";
import "@mantine/core/styles.css";

import {
  ColorSchemeScript,
  MantineProvider,
  createTheme,
  mantineHtmlProps,
} from "@mantine/core";
import { ThemeModeScript } from "flowbite-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mi tiendita",
  description: "Generated by create next app",
};
const theme = createTheme({
  white: "light",
  black: "dark",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark" {...mantineHtmlProps} suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
        <ThemeModeScript /> 
      </head>
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider theme={theme}>
          <ActionsProvider>
            <Providers>{children}</Providers>
          </ActionsProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
