
import { Geist, Geist_Mono } from "next/font/google";
import Providers from "@/context/Providers";
import "@/styles/main.scss";
import { ActionsProvider } from "@/context/actionsProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mi tiendita",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ActionsProvider>
          <Providers>{children}</Providers>
        </ActionsProvider>
      </body>
    </html>
  );
}
